name: Publish package

on:
  release:
    types:
      - published

jobs:
  publish-gpr:
    runs-on:
      group: thulium-ubuntu-runners
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.3

      - name: Set up Node.js 18.13.0
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 20.17.0
          registry-url: https://npm.pkg.github.com/

      - name: Install dependencies
        run: npm ci

      - name: Build production
        run: npm run release

      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
